"""
Dashboard orchestrator: build topic correlation outputs for window metrics.

Metrics grouped by:
- Unexpectedness: avg_token_surprisal, max_token_surprisal, surprisal_variance
- Lexical: lexical_density_per_token, lexical_diversity_mattr, avg_word_freq, normalized_freq, information_content
- Structure: max_dependency_depth, clause_density, avg_dependents_per_head,
  clause_ratios, avg_mean_dependency_distance, avg_median_depth, depth_skew, punctuation_per_token
- Discourse: explicit_connectives_per_token, modality_per_token, connective_counts_per_token, tense_shift, entity_overlap_rate

Assumes window metrics exist under data/analytics/window_metrics/<category>/<name>/
generated by d_window_metrics.run_windowed_metrics.
"""

import json
import math
import statistics
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from tqdm import tqdm

from src.d1_dashboard_metrics import (
    build_central_report,
    build_topic_correlation_report,
    collect_window_tables,
    compute_metric_variances,
    central_topics,
    load_window_metrics,
)
from z_utils import find_topic_file, find_window_metrics_files, results_path

TEXT_CENTRAL_TOPIC_SCORES_FILENAME = "00_texts_central_topic_scores.json"
GENRE_METRIC_VARIANCE_FILENAME = "00_genre_metric_variance_correlations.json"
GENRE_TOPIC_SCORES_FILENAME = "00_genre_topic_scores.json"
GENRE_CENTRAL_PRESENCE_FILENAME = "00_genre_central_topic_presence_correlations.json"


def _as_float(value: object) -> Optional[float]:
    if not isinstance(value, (int, float)):
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    return float(value)


def _as_count(value: object) -> Optional[int]:
    numeric = _as_float(value)
    if numeric is None:
        return None
    count = int(numeric)
    if count <= 0:
        return None
    return count


def _fisher_z(value: float) -> Optional[float]:
    if value <= -1.0 or value >= 1.0:
        value = max(min(value, 0.999999), -0.999999)
    return math.atanh(value)


def _stouffer_p_value(rows: List[Tuple[float, float, int]]) -> Optional[float]:
    if not rows:
        return None
    normal = statistics.NormalDist()
    weighted = []
    for r_value, p_value, n_value in rows:
        if n_value <= 3:
            continue
        p_value = max(min(p_value, 1.0 - 1e-15), 1e-15)
        z_value = normal.inv_cdf(1.0 - p_value / 2.0)
        if r_value < 0:
            z_value = -z_value
        weight = math.sqrt(n_value - 3)
        weighted.append((weight, z_value))
    if not weighted:
        return None
    denom = math.sqrt(sum(weight ** 2 for weight, _ in weighted))
    if denom <= 0:
        return None
    z_combined = sum(weight * z_value for weight, z_value in weighted) / denom
    return 2.0 * (1.0 - normal.cdf(abs(z_combined)))


def _build_text_central_topic_scores(
    window_metrics_path: Path,
    *,
    central_top_n: int,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None
    topics_data = load_window_metrics(topic_file)
    central_ranked = central_topics(topics_data, top_n=central_top_n)
    if not central_ranked:
        return None

    genre = window_metrics_path.parent.parent.parent.name
    author = window_metrics_path.parent.parent.name
    text_name = window_metrics_path.parent.name
    category = f"{genre}/{author}"

    return {
        "category": category,
        "genre": genre,
        "author": author,
        "text_name": text_name,
        "topic_file": str(topic_file),
        "central_topics": central_ranked,
    }


def _build_text_metric_variance_entry(
    window_metrics_path: Path,
) -> Optional[Dict[str, object]]:
    window_data = load_window_metrics(window_metrics_path)
    window_table = collect_window_tables(window_data)
    if not window_table:
        return None
    variances = compute_metric_variances(window_table)
    if not variances:
        return None

    genre = window_metrics_path.parent.parent.parent.name
    author = window_metrics_path.parent.parent.name
    text_name = window_metrics_path.parent.name
    category = f"{genre}/{author}"

    return {
        "category": category,
        "genre": genre,
        "author": author,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "window_metrics_file": str(window_metrics_path),
        "window_count": len(window_table),
        "metric_variances": variances,
    }


def _summarize_metric_variances(
    entries: List[Dict[str, object]],
) -> Dict[str, Dict[str, float]]:
    values_by_metric: Dict[str, List[float]] = {}
    for entry in entries:
        variances = entry.get("metric_variances", {})
        if not isinstance(variances, dict):
            continue
        for metric, value in variances.items():
            if isinstance(value, (int, float)):
                values_by_metric.setdefault(metric, []).append(float(value))

    summary: Dict[str, Dict[str, float]] = {}
    for metric, values in values_by_metric.items():
        if not values:
            continue
        summary[metric] = {
            "mean_text_variance": statistics.mean(values),
            "median_text_variance": statistics.median(values),
            "min_text_variance": min(values),
            "max_text_variance": max(values),
            "text_count": len(values),
        }
    return summary


def _group_by_genre(entries: List[Dict[str, object]]) -> Dict[str, List[Dict[str, object]]]:
    grouped: Dict[str, List[Dict[str, object]]] = {}
    for entry in entries:
        genre = entry.get("genre")
        if not isinstance(genre, str):
            continue
        grouped.setdefault(genre, []).append(entry)
    return grouped


def _sorted_text_entries(entries: List[Dict[str, object]]) -> List[Dict[str, object]]:
    return sorted(
        entries,
        key=lambda row: (row.get("genre", ""), row.get("author", ""), row.get("text_name", "")),
    )


def _write_text_central_topic_scores(
    entries: List[Dict[str, object]],
    *,
    use_existing: bool,
) -> None:
    if not entries:
        return
    output_path = results_path("dashboard", filename=TEXT_CENTRAL_TOPIC_SCORES_FILENAME)
    if use_existing and output_path.exists():
        return
    payload = {
        "text_count": len(entries),
        "texts": _sorted_text_entries(entries),
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)


def _write_genre_topic_scores(
    entries: List[Dict[str, object]],
    *,
    use_existing: bool,
) -> None:
    if not entries:
        return
    for genre, genre_entries in _group_by_genre(entries).items():
        output_path = results_path("dashboard", category=genre, filename=GENRE_TOPIC_SCORES_FILENAME)
        if use_existing and output_path.exists():
            continue
        sorted_entries = sorted(
            genre_entries,
            key=lambda row: (row.get("author", ""), row.get("text_name", "")),
        )
        payload = {
            "genre": genre,
            "text_count": len(genre_entries),
            "texts": sorted_entries,
        }
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)


def _write_genre_metric_variances(
    entries: List[Dict[str, object]],
    *,
    use_existing: bool,
) -> None:
    if not entries:
        return
    for genre, genre_entries in _group_by_genre(entries).items():
        output_path = results_path("dashboard", category=genre, filename=GENRE_METRIC_VARIANCE_FILENAME)
        if use_existing and output_path.exists():
            continue
        summary = _summarize_metric_variances(genre_entries)
        payload = {
            "genre": genre,
            "text_count": len(genre_entries),
            "metric_names": sorted(summary.keys()),
            "metrics": summary,
            "texts": sorted(
                genre_entries,
                key=lambda row: (row.get("author", ""), row.get("text_name", "")),
            ),
        }
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)


def _aggregate_central_presence_correlations(
    entries: List[Dict[str, object]],
) -> Dict[str, object]:
    metrics: Dict[str, List[Tuple[float, float, int]]] = {}
    texts: List[Dict[str, object]] = []
    for entry in entries:
        central_report = entry.get("central_report", {})
        if not isinstance(central_report, dict):
            continue
        presence = central_report.get("central_topic_presence", {})
        if not isinstance(presence, dict):
            continue
        correlations = presence.get("correlations", {})
        if not isinstance(correlations, dict) or not correlations:
            continue

        window_count = _as_count(central_report.get("window_count"))
        if window_count is None:
            for corr_entry in correlations.values():
                if isinstance(corr_entry, dict):
                    window_count = _as_count(corr_entry.get("n"))
                    if window_count is not None:
                        break
        texts.append(
            {
                "category": entry.get("category"),
                "author": entry.get("author"),
                "text_name": entry.get("text_name"),
                "filename": entry.get("filename"),
                "window_count": window_count,
                "metric_count": len(correlations),
            }
        )

        for metric, corr_entry in correlations.items():
            if not isinstance(corr_entry, dict):
                continue
            r_value = _as_float(corr_entry.get("pearson_r"))
            p_value = _as_float(corr_entry.get("p_value"))
            n_value = _as_count(corr_entry.get("n"))
            if r_value is None or p_value is None or n_value is None:
                continue
            metrics.setdefault(metric, []).append((r_value, p_value, n_value))

    aggregated: Dict[str, object] = {}
    for metric, rows in metrics.items():
        valid_rows = [(r, p, n) for r, p, n in rows if n > 3]
        if not valid_rows:
            continue
        weights = [(n - 3) for _, _, n in valid_rows]
        z_values = [_fisher_z(r) for r, _, _ in valid_rows]
        if any(z is None for z in z_values):
            continue
        weight_sum = sum(weights)
        if weight_sum <= 0:
            continue
        z_bar = sum(z * w for z, w in zip(z_values, weights)) / weight_sum
        r_bar = math.tanh(z_bar)
        p_combined = _stouffer_p_value(valid_rows)
        aggregated[metric] = {
            "pearson_r": r_bar,
            "p_value": p_combined,
            "text_count": len(valid_rows),
            "total_windows": sum(n for _, _, n in valid_rows),
            "fisher_z": z_bar,
            "fisher_z_weight_sum": weight_sum,
        }

    return {
        "metric_names": sorted(aggregated.keys()),
        "metrics": aggregated,
        "texts": sorted(
            texts,
            key=lambda row: (row.get("category", ""), row.get("text_name", "")),
        ),
    }


def _write_genre_central_presence_correlations(
    entries: List[Dict[str, object]],
    *,
    use_existing: bool,
) -> None:
    if not entries:
        return
    for genre, genre_entries in _group_by_genre(entries).items():
        output_path = results_path("dashboard", category=genre, filename=GENRE_CENTRAL_PRESENCE_FILENAME)
        if use_existing and output_path.exists():
            continue
        summary = _aggregate_central_presence_correlations(genre_entries)
        payload = {
            "genre": genre,
            "text_count": len(summary.get("texts", [])),
            "metric_names": summary.get("metric_names", []),
            "metrics": summary.get("metrics", {}),
            "texts": summary.get("texts", []),
            "params": {
                "r_aggregation": "fisher_z",
                "p_value_aggregation": "stouffer",
                "r_weight": "n-3",
                "p_weight": "sqrt(n-3)",
            },
        }
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)


def _build_topic_dashboard_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    report = build_topic_correlation_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        topics_key="topics",
        block_size=block_size,
        permutations=permutations,
    )
    if not report:
        return None

    central_report = build_central_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "report": report,
        "central_topics": central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }

def _build_central_topic_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    central_report = build_central_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "central_topics": central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }

def run_dashboard(
    use_existing: bool = False,
    *,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_top_n: int = 5,
    block_size: int = 5,
    permutations: int = 2000,
    authors: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    """
    Build topic correlation outputs from window metrics and write JSON outputs.

    Outputs (per text):
      data/results/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
    Outputs (aggregates):
      data/results/dashboard/<genre>/00_genre_central_topic_presence_correlations.json
    """
    output_root = results_path("dashboard")
    output_root.mkdir(parents=True, exist_ok=True)

    window_metric_files = find_window_metrics_files()
    if authors:
        window_metric_files = [
            file for file in window_metric_files if file.parent.parent.name in authors
        ]
    if not window_metric_files:
        return []
    central_presence_entries: List[Dict[str, object]] = []

    for file in tqdm(window_metric_files, desc="Dashboard correlations", ascii=True):
        genre = file.parent.parent.parent.name
        author = file.parent.parent.name
        text_name = file.parent.name
        out_dir = output_root / genre / author / text_name
        out_dir.mkdir(parents=True, exist_ok=True)

        topic_file = out_dir / f"{text_name}_topic_correlations.json"
        central_file = out_dir / f"{text_name}_central_topic_correlations.json"
        topic_entry = None
        if use_existing and topic_file.exists():
            try:
                with open(topic_file, "r", encoding="utf-8") as f:
                    topic_entry = json.load(f)
            except json.JSONDecodeError:
                topic_entry = None
        if topic_entry is None:
            topic_entry = _build_topic_dashboard_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
            if topic_entry:
                with open(topic_file, "w", encoding="utf-8") as f:
                    json.dump(topic_entry, f, indent=2)

        central_entry = None
        if use_existing and central_file.exists():
            try:
                with open(central_file, "r", encoding="utf-8") as f:
                    central_entry = json.load(f)
            except json.JSONDecodeError:
                central_entry = None
        if central_entry is None:
            central_entry = _build_central_topic_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
        if central_entry:
            with open(central_file, "w", encoding="utf-8") as f:
                json.dump(central_entry, f, indent=2)
            central_report = central_entry.get("central_report")
            if isinstance(central_report, dict):
                central_presence_entries.append(
                    {
                        "category": f"{genre}/{author}",
                        "genre": genre,
                        "author": author,
                        "text_name": text_name,
                        "filename": file.name,
                        "central_report": central_report,
                    }
                )

    _write_genre_central_presence_correlations(
        central_presence_entries,
        use_existing=use_existing,
    )

    return []

if __name__ == "__main__":
    run_dashboard()
