"""
Dashboard orchestrator: build topic correlation outputs for window metrics.

Metrics grouped by:
- Unexpectedness: avg_token_surprisal, max_token_surprisal, surprisal_variance
- Lexical: lexical_density_per_token, lexical_diversity_mattr, avg_word_freq, normalized_freq, information_content
- Structure: max_dependency_depth, clause_density, avg_dependents_per_head.<clause_type>,
  clause_ratios, avg_mean_dependency_distance, avg_median_depth, depth_skew, punctuation_per_token
- Discourse: explicit_connectives_per_token, modality_per_token, connective_counts_per_token, tense_shift, entity_overlap_rate
- Variance: variance.<domain>_rms_z, variance.overall_rms_z

Assumes window metrics exist under data/analytics/window_metrics/<category>/<name>/
as standardized split domain files (window_metrics.<domain>.json) generated by
f_orchestrator.run_windowed_metrics.

Outputs (per text):
- data/results/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "total_topics": int,
      "window_count": int,
      "metric_names": [str],
      "topics": {
        "<topic_id>": {
          "keywords": [str],
          "correlations": {
            "<metric>": {
              "pearson_r": float,
              "p_value": float
            }
          }
        }
      }
    },
    "params": {
      "near_top_alpha": float,
      "top_score_fraction": float,
      "coherence_floor": float,
      "exclusivity_floor": float,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "centrality_metrics_order": [str],
      "central_topics": [
        {
          "topic_id": int,
          "score": float,
          "raw_score": [float|null],
          "percentile_score": [float|null],
          "keywords": [str],
          "correlations": {
            "<metric>": {
              "pearson_r": float,
              "p_value": float
            }
          }
        }
      ]
    },
    "params": {
      "near_top_alpha": float,
      "top_score_fraction": float,
      "coherence_floor": float,
      "exclusivity_floor": float,
      "block_size": int,
      "permutations": int
    }
  }

Centrality metrics include top10_mean (mean of the top fraction of per-window topic scores).
Central topic selection applies coherence/exclusivity percentile floors before near_top_alpha.

All-central-topic (p-norm) correlations use the normalized p-norm across central topics per window
(default p comes from config, dividing by K, the number of central topics).
All-topic (p-norm) correlations use the normalized p-norm across all topics per window
(default p comes from config, dividing by K; K defaults to the central-topic count for k-matched comparisons).
All-non-central-topic (p-norm) correlations use the normalized p-norm across non-central topics
per window (default p comes from config, dividing by K; K defaults to the central-topic count for k-matching).

- data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_presence_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "central_topic_presence": {
        "central_presence_scores": [float],
        "correlations": {
          "<metric>": {
            "pearson_r": float,
            "p_value": float
          }
        }
      }
    },
    "params": {
      "presence_aggregation": "p_norm",
      "presence_p": float,
      "presence_normalized": bool,
      "presence_k_reference": str,
      "presence_k": int,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_topic_presence_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "topic_presence": {
        "topic_presence_scores": [float],
        "correlations": {
          "<metric>": {
            "pearson_r": float,
            "p_value": float
          }
        }
      }
    },
    "params": {
      "presence_aggregation": "p_norm",
      "presence_p": float,
      "presence_normalized": bool,
      "presence_k_reference": str,
      "presence_k": int,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_non_central_topic_presence_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "non_central_topic_presence": {
        "non_central_presence_scores": [float],
        "correlations": {
          "<metric>": {
            "pearson_r": float,
            "p_value": float
          }
        }
      }
    },
    "params": {
      "presence_aggregation": "p_norm",
      "presence_p": float,
      "presence_normalized": bool,
      "presence_k_reference": str,
      "presence_k": int,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_window_variances.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str
    },
    "report": {
      "window_count": int|null,
      "window_counts": {"syntax": int, "lexico_semantics": int, "discourse": int, "log_prob": int},
      "metric_variances": {"syntax": {"metric": float}, "...": "..."},
      "metric_counts": {"syntax": int, "...": "..."},
      "rms_z": {
        "domain_means": {"syntax": float, "...": "..."},
        "domain_variances": {"syntax": float, "...": "..."},
        "overall_mean": float|null,
        "overall_variance": float|null,
        "metric_counts": {"syntax": int, "...": "..."},
        "overall_metric_count": int
      }
    },
    "params": {
      "metric_variance_method": "pvariance",
      "rms_z_method": "rms_z",
      "rms_z_variance_method": "pvariance"
    }
  }

Outputs (aggregates, under output_root):
- <output_root>/<genre>/00_genre_central_topic_presence_correlations.json
  {
    "genre": str,
    "text_count": int,
    "metric_names": [str],
    "metrics": {
      "<metric>": {
        "pearson_r": float,
        "p_value": float,
        "text_count": int,
        "total_windows": int,
        "total_effective_windows": int,
        "fisher_z": float,
        "fisher_z_weight_sum": float
      }
    },
    "texts": [
      {
        "category": str,
        "author": str,
        "text_name": str,
        "filename": str,
        "window_count": int|null,
        "effective_window_count": int|null,
        "block_size": int|null,
        "metric_count": int
      }
    ],
    "params": {
      "r_aggregation": "fisher_z",
      "p_value_aggregation": "stouffer",
      "r_weight": "n_eff-3",
      "p_weight": "sqrt(n_eff-3)",
      "n_eff_method": "ceil(n_windows / block_size), min 1",
      "block_size": int|[int]
    }
  }

- <output_root>/00_central_topic_split_half_stability.json
  {
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [
      {
        "category": str,
        "text_name": str,
        "filename": str,
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    ],
    "params": {
      "split_method": "odd_even"
    }
  }

- <output_root>/<genre>/00_genre_central_topic_split_half_stability.json
  {
    "genre": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even"
    }
  }

- <output_root>/<genre>/<author>/<author>_central_topic_split_half_stability.json
  {
    "genre": str,
    "author": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even"
    }
  }

- <output_root>/00_central_topic_presence_split_half_stability.json
  {
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [
      {
        "category": str,
        "text_name": str,
        "filename": str,
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    ],
    "params": {
      "split_method": "odd_even"
    }
  }

- <output_root>/<genre>/00_genre_central_topic_presence_split_half_stability.json
  {
    "genre": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even"
    }
  }

- <output_root>/<genre>/<author>/<author>_central_topic_presence_split_half_stability.json
  {
    "genre": str,
    "author": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even"
    }
  }

- data/results/00_cross_block_consistency.json
  {
    "block_labels": [str],
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "params": {
      "block_labels": [str],
      "output_roots": [str]
    }
  }
"""

import json
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

from tqdm import tqdm

from .d0_significance_stability import (
    _build_central_presence_split_half_entry,
    _build_central_topic_split_half_entry,
    _build_topic_split_half_entry,
    _write_author_central_presence_split_half_summary,
    _write_author_central_topic_split_half_summary,
    _write_author_topic_split_half_summary,
    _write_central_presence_split_half_summary,
    _write_central_topic_split_half_summary,
    _write_topic_split_half_summary,
    _write_cross_block_consistency_summary,
    _write_genre_central_presence_correlations,
    _write_genre_central_presence_split_half_summary,
    _write_genre_central_topic_split_half_summary,
    _write_genre_topic_split_half_summary,
)
from .d1_dashboard_metrics import (
    build_central_presence_report,
    build_central_topic_correlations,
    build_non_central_presence_report,
    build_topic_presence_report,
    build_topic_correlation_report,
    build_window_variance_report,
    load_window_metrics,
)
from .x_configs import (
    AUTHOR_CENTRAL_PRESENCE_SPLIT_HALF_TEMPLATE,
    AUTHOR_CENTRAL_TOPIC_SPLIT_HALF_TEMPLATE,
    AUTHOR_TOPIC_SPLIT_HALF_TEMPLATE,
    CENTRAL_PRESENCE_SPLIT_HALF_FILENAME,
    CENTRAL_TOPIC_CORRELATIONS_SUFFIX,
    CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX,
    CENTRAL_TOPIC_SPLIT_HALF_FILENAME,
    DEFAULT_USE_EXISTING,
    DEFAULT_BLOCK_SIZE,
    DEFAULT_DASHBOARD_CORRELATION_CONFIG,
    DEFAULT_DASHBOARD_PERMUTATIONS,
    GENRE_CENTRAL_PRESENCE_SPLIT_HALF_FILENAME,
    GENRE_CENTRAL_TOPIC_SPLIT_HALF_FILENAME,
    GENRE_TOPIC_SPLIT_HALF_FILENAME,
    NON_CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX,
    TOPIC_PRESENCE_CORRELATIONS_SUFFIX,
    TOPIC_CORRELATIONS_SUFFIX,
    TOPIC_SPLIT_HALF_FILENAME,
    WINDOW_VARIANCE_SUFFIX,
    DashboardCorrelationConfig,
)
from .z_utils import (
    block_results_path,
    dashboard_report_candidates,
    dashboard_report_path,
    find_topic_file,
    find_window_metrics_files,
    load_json,
    results_path,
)


def _split_report_params(report: Dict[str, object]) -> Tuple[Dict[str, object], Dict[str, object]]:
    if not isinstance(report, dict):
        return {}, {}
    params = report.get("params")
    if not isinstance(params, dict):
        params = {}
    report_body = {key: value for key, value in report.items() if key != "params"}
    return report_body, params


def _build_metadata(window_metrics_path: Path, topic_file: Path) -> Dict[str, object]:
    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name
    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
    }


def _build_window_metadata(window_metrics_path: Path) -> Dict[str, object]:
    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name
    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
    }


def _report_path_candidates(base_dir: Path, text_name: str, suffix: str) -> List[Path]:
    return dashboard_report_candidates(base_dir, text_name, suffix)


def _report_output_path(base_dir: Path, suffix: str) -> Path:
    return base_dir / f"text{suffix}"


def _existing_report_path(base_dir: Path, text_name: str, suffix: str) -> Path:
    return dashboard_report_path(base_dir, text_name, suffix)


def _build_dashboard_entry(
    window_metrics_path: Path,
    *,
    report_builder: Callable[..., Dict[str, object]],
    builder_kwargs: Dict[str, object],
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_json(topic_file)
    if not isinstance(topics_data, dict):
        return None

    metadata = _build_metadata(window_metrics_path, topic_file)
    report = report_builder(window_data, topics_data, **builder_kwargs)
    if not report:
        syntax_windows = []
        if isinstance(window_data, dict):
            syntax_payload = window_data.get("syntax", {})
            if isinstance(syntax_payload, dict):
                candidate_windows = syntax_payload.get("windows", [])
                if isinstance(candidate_windows, list):
                    syntax_windows = candidate_windows
        topic_windows = topics_data.get("windows", []) if isinstance(topics_data, dict) else []
        return {
            "metadata": metadata,
            "report": {
                "window_count": len(syntax_windows),
                "metric_names": [],
                "coverage": {
                    "status": "insufficient_topic_signal",
                    "reason": "No aligned topic-presence correlations could be computed for this text.",
                    "topic_window_count": len(topic_windows) if isinstance(topic_windows, list) else 0,
                },
            },
            "params": dict(builder_kwargs),
        }

    report_body, params = _split_report_params(report)
    return {
        "metadata": metadata,
        "report": report_body,
        "params": params,
    }


def _build_topic_dashboard_entry(
    window_metrics_path: Path,
    *,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    return _build_dashboard_entry(
        window_metrics_path,
        report_builder=build_topic_correlation_report,
        builder_kwargs={
            "topics_key": "topics",
            "block_size": block_size,
            "permutations": permutations,
        },
    )

def _build_central_topic_entry(
    window_metrics_path: Path,
    *,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    return _build_dashboard_entry(
        window_metrics_path,
        report_builder=build_central_topic_correlations,
        builder_kwargs={
            "block_size": block_size,
            "permutations": permutations,
        },
    )


def _build_central_presence_entry(
    window_metrics_path: Path,
    *,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    return _build_dashboard_entry(
        window_metrics_path,
        report_builder=build_central_presence_report,
        builder_kwargs={
            "block_size": block_size,
            "permutations": permutations,
        },
    )


def _build_topic_presence_entry(
    window_metrics_path: Path,
    *,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    return _build_dashboard_entry(
        window_metrics_path,
        report_builder=build_topic_presence_report,
        builder_kwargs={
            "block_size": block_size,
            "permutations": permutations,
        },
    )


def _build_non_central_presence_entry(
    window_metrics_path: Path,
    *,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    return _build_dashboard_entry(
        window_metrics_path,
        report_builder=build_non_central_presence_report,
        builder_kwargs={
            "block_size": block_size,
            "permutations": permutations,
        },
    )

def run_dashboard(
    use_existing: bool = DEFAULT_USE_EXISTING,
    *,
    block_size: int = DEFAULT_BLOCK_SIZE,
    permutations: int = DEFAULT_DASHBOARD_PERMUTATIONS,
    output_root: Optional[Path] = None,
    authors: Optional[List[str]] = None,
    texts: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    """
    Build topic correlation outputs from window metrics and write JSON outputs.
    Optionally filter by author or text name for targeted runs.

    Outputs (per text):
      data/results/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_presence_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_topic_presence_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_non_central_topic_presence_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_window_variances.json
    Outputs (aggregates):
      data/results/dashboard/<genre>/00_genre_central_topic_presence_correlations.json
    """
    if output_root is None:
        output_root = results_path("dashboard", block_size=block_size)
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    window_metric_files = find_window_metrics_files()
    text_filter = set(texts) if texts else None
    if authors:
        window_metric_files = [
            file for file in window_metric_files if file.parent.parent.name in authors
        ]
    if text_filter:
        window_metric_files = [
            file for file in window_metric_files if file.parent.name in text_filter
        ]
    if not window_metric_files:
        return []

    skip_topic_split_half = False
    skip_all_topic_split_half = False
    skip_presence_split_half = False
    if use_existing:
        genre_author_pairs = {
            (file.parent.parent.parent.name, file.parent.parent.name)
            for file in window_metric_files
        }
        topic_split_half_output_path = output_root / CENTRAL_TOPIC_SPLIT_HALF_FILENAME
        topic_genre_outputs = {
            output_root / genre / GENRE_CENTRAL_TOPIC_SPLIT_HALF_FILENAME
            for genre, _author in genre_author_pairs
        }
        topic_author_outputs = {
            output_root
            / genre
            / author
            / AUTHOR_CENTRAL_TOPIC_SPLIT_HALF_TEMPLATE.format(author=author)
            for genre, author in genre_author_pairs
        }
        skip_topic_split_half = (
            topic_split_half_output_path.exists()
            and all(path.exists() for path in topic_genre_outputs)
            and all(path.exists() for path in topic_author_outputs)
        )
        all_topic_split_half_output_path = output_root / TOPIC_SPLIT_HALF_FILENAME
        all_topic_genre_outputs = {
            output_root / genre / GENRE_TOPIC_SPLIT_HALF_FILENAME
            for genre, _author in genre_author_pairs
        }
        all_topic_author_outputs = {
            output_root
            / genre
            / author
            / AUTHOR_TOPIC_SPLIT_HALF_TEMPLATE.format(author=author)
            for genre, author in genre_author_pairs
        }
        skip_all_topic_split_half = (
            all_topic_split_half_output_path.exists()
            and all(path.exists() for path in all_topic_genre_outputs)
            and all(path.exists() for path in all_topic_author_outputs)
        )
        presence_split_half_output_path = output_root / CENTRAL_PRESENCE_SPLIT_HALF_FILENAME
        presence_genre_outputs = {
            output_root / genre / GENRE_CENTRAL_PRESENCE_SPLIT_HALF_FILENAME
            for genre, _author in genre_author_pairs
        }
        presence_author_outputs = {
            output_root
            / genre
            / author
            / AUTHOR_CENTRAL_PRESENCE_SPLIT_HALF_TEMPLATE.format(author=author)
            for genre, author in genre_author_pairs
        }
        skip_presence_split_half = (
            presence_split_half_output_path.exists()
            and all(path.exists() for path in presence_genre_outputs)
            and all(path.exists() for path in presence_author_outputs)
        )
    central_presence_entries: List[Dict[str, object]] = []
    topic_split_half_entries: List[Dict[str, object]] = []
    split_half_entries: List[Dict[str, object]] = []
    presence_split_half_entries: List[Dict[str, object]] = []

    for file in tqdm(window_metric_files, desc="Dashboard correlations", ascii=True):
        genre = file.parent.parent.parent.name
        author = file.parent.parent.name
        text_name = file.parent.name
        out_dir = output_root / genre / author / text_name
        out_dir.mkdir(parents=True, exist_ok=True)

        topic_file = _report_output_path(out_dir, TOPIC_CORRELATIONS_SUFFIX)
        central_file = _report_output_path(out_dir, CENTRAL_TOPIC_CORRELATIONS_SUFFIX)
        presence_file = _report_output_path(out_dir, CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX)
        topic_presence_file = _report_output_path(out_dir, TOPIC_PRESENCE_CORRELATIONS_SUFFIX)
        non_central_presence_file = _report_output_path(
            out_dir,
            NON_CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX,
        )
        variance_file = _report_output_path(out_dir, WINDOW_VARIANCE_SUFFIX)

        topic_existing_file = _existing_report_path(out_dir, text_name, TOPIC_CORRELATIONS_SUFFIX)
        central_existing_file = _existing_report_path(out_dir, text_name, CENTRAL_TOPIC_CORRELATIONS_SUFFIX)
        presence_existing_file = _existing_report_path(out_dir, text_name, CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX)
        topic_presence_existing_file = _existing_report_path(out_dir, text_name, TOPIC_PRESENCE_CORRELATIONS_SUFFIX)
        non_central_presence_existing_file = _existing_report_path(
            out_dir,
            text_name,
            NON_CENTRAL_TOPIC_PRESENCE_CORRELATIONS_SUFFIX,
        )
        variance_existing_file = _existing_report_path(out_dir, text_name, WINDOW_VARIANCE_SUFFIX)

        topic_entry = None
        if use_existing and topic_existing_file.exists():
            try:
                with open(topic_existing_file, "r", encoding="utf-8") as f:
                    topic_entry = json.load(f)
            except json.JSONDecodeError:
                topic_entry = None
        if topic_entry is None:
            topic_entry = _build_topic_dashboard_entry(
                file,
                block_size=block_size,
                permutations=permutations,
            )
            if topic_entry:
                with open(topic_file, "w", encoding="utf-8") as f:
                    json.dump(topic_entry, f, indent=2)
        if topic_entry and not skip_all_topic_split_half:
            topic_split_half_entry = _build_topic_split_half_entry(
                file,
                topic_entry,
            )
            if topic_split_half_entry:
                topic_split_half_entries.append(topic_split_half_entry)

        central_entry = None
        if use_existing and central_existing_file.exists():
            try:
                with open(central_existing_file, "r", encoding="utf-8") as f:
                    central_entry = json.load(f)
            except json.JSONDecodeError:
                central_entry = None
        if central_entry is None:
            central_entry = _build_central_topic_entry(
                file,
                block_size=block_size,
                permutations=permutations,
            )
        if central_entry:
            with open(central_file, "w", encoding="utf-8") as f:
                json.dump(central_entry, f, indent=2)
            if not skip_topic_split_half:
                split_half_entry = _build_central_topic_split_half_entry(
                    file,
                    central_entry,
                )
                if split_half_entry:
                    split_half_entries.append(split_half_entry)

        topic_presence_entry = None
        if use_existing and topic_presence_existing_file.exists():
            try:
                with open(topic_presence_existing_file, "r", encoding="utf-8") as f:
                    topic_presence_entry = json.load(f)
            except json.JSONDecodeError:
                topic_presence_entry = None
        if topic_presence_entry is None:
            topic_presence_entry = _build_topic_presence_entry(
                file,
                block_size=block_size,
                permutations=permutations,
            )
        if topic_presence_entry:
            with open(topic_presence_file, "w", encoding="utf-8") as f:
                json.dump(topic_presence_entry, f, indent=2)

        non_central_presence_entry = None
        if use_existing and non_central_presence_existing_file.exists():
            try:
                with open(non_central_presence_existing_file, "r", encoding="utf-8") as f:
                    non_central_presence_entry = json.load(f)
            except json.JSONDecodeError:
                non_central_presence_entry = None
        if non_central_presence_entry is None:
            non_central_presence_entry = _build_non_central_presence_entry(
                file,
                block_size=block_size,
                permutations=permutations,
            )
        if non_central_presence_entry:
            with open(non_central_presence_file, "w", encoding="utf-8") as f:
                json.dump(non_central_presence_entry, f, indent=2)

        presence_entry = None
        if use_existing and presence_existing_file.exists():
            try:
                with open(presence_existing_file, "r", encoding="utf-8") as f:
                    presence_entry = json.load(f)
            except json.JSONDecodeError:
                presence_entry = None
        if presence_entry is None:
            presence_entry = _build_central_presence_entry(
                file,
                block_size=block_size,
                permutations=permutations,
            )
        if presence_entry:
            with open(presence_file, "w", encoding="utf-8") as f:
                json.dump(presence_entry, f, indent=2)
            central_presence_entries.append(
                {
                    "category": f"{genre}/{author}",
                    "genre": genre,
                    "author": author,
                    "text_name": text_name,
                    "filename": file.name,
                    "presence_report": presence_entry,
                }
            )
            if not skip_presence_split_half:
                presence_split_half_entry = _build_central_presence_split_half_entry(
                    file,
                    presence_entry,
                )
                if presence_split_half_entry:
                    presence_split_half_entries.append(presence_split_half_entry)

        variance_entry = None
        if use_existing and variance_existing_file.exists():
            try:
                with open(variance_existing_file, "r", encoding="utf-8") as f:
                    variance_entry = json.load(f)
            except json.JSONDecodeError:
                variance_entry = None
        if variance_entry is None:
            window_data = load_window_metrics(file)
            variance_report = build_window_variance_report(window_data)
            if variance_report:
                variance_entry = {
                    "metadata": _build_window_metadata(file),
                    "report": variance_report,
                }
                with open(variance_file, "w", encoding="utf-8") as f:
                    json.dump(variance_entry, f, indent=2)

    _write_genre_central_presence_correlations(
        central_presence_entries,
        use_existing=use_existing,
        output_root=output_root,
    )
    if not skip_all_topic_split_half:
        _write_topic_split_half_summary(
            topic_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_genre_topic_split_half_summary(
            topic_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_author_topic_split_half_summary(
            topic_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
    if not skip_topic_split_half:
        _write_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_genre_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_author_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
    if not skip_presence_split_half:
        _write_central_presence_split_half_summary(
            presence_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_genre_central_presence_split_half_summary(
            presence_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_author_central_presence_split_half_summary(
            presence_split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )

    return []

def run_dashboard_with_config(
    use_existing: bool = DEFAULT_USE_EXISTING,
    *,
    authors: Optional[List[str]] = None,
    texts: Optional[List[str]] = None,
    config: DashboardCorrelationConfig = DEFAULT_DASHBOARD_CORRELATION_CONFIG,
) -> List[Dict[str, object]]:
    if config.loop_enabled:
        block_sizes = list(config.loop_block_sizes or ())
        if not block_sizes:
            block_sizes = [config.block_size]
        output_roots: List[Path] = []
        block_labels: List[str] = []
        for block_size in block_sizes:
            output_root = block_results_path(
                "dashboard",
                block_size,
                template=config.loop_output_template,
            )
            output_roots.append(output_root)
            block_labels.append(output_root.name)
            run_dashboard(
                use_existing=use_existing,
                block_size=block_size,
                permutations=config.permutations,
                output_root=output_root,
                authors=authors,
                texts=texts,
            )
        _write_cross_block_consistency_summary(
            output_roots,
            block_labels,
            use_existing=use_existing,
        )
        return []

    return run_dashboard(
        use_existing=use_existing,
        block_size=config.block_size,
        permutations=config.permutations,
        authors=authors,
        texts=texts,
    )

if __name__ == "__main__":
    run_dashboard_with_config()
