"""
Dashboard orchestrator: build topic correlation outputs for window metrics.

Metrics grouped by:
- Unexpectedness: avg_token_surprisal, max_token_surprisal, surprisal_variance
- Lexical: lexical_density_per_token, lexical_diversity_mattr, avg_word_freq, normalized_freq, information_content
- Structure: max_dependency_depth, clause_density, avg_dependents_per_head,
  clause_ratios, avg_mean_dependency_distance, avg_median_depth, depth_skew, punctuation_per_token
- Discourse: explicit_connectives_per_token, modality_per_token, connective_counts_per_token, tense_shift, entity_overlap_rate

Assumes window metrics exist under data/analytics/window_metrics/<category>/<name>/
generated by d_window_metrics.run_windowed_metrics.

Outputs (per text):
- data/results/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "total_topics": int,
      "window_count": int,
      "metric_names": [str],
      "topics": {
        "<topic_id>": {
          "keywords": [str],
          "windows_with_topic": int,
          "windows_without_topic": int,
          "correlations": {
            "<metric>": {
              "pearson_r": float,
              "p_value": float,
              "pearson_r_binary": float,
              "p_value_binary": float,
              "n_windows": int,
              "mean_with_topic": float,
              "mean_without_topic": float
            }
          }
        }
      }
    },
    "params": {
      "use_soft_topic_scores": bool,
      "soft_score_threshold": float|null,
      "soft_top_k": int|null,
      "central_top_n": int|null,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "centrality_metrics_order": [str],
      "central_topics": [
        {
          "topic_id": int,
          "score": float,
          "raw_score": [float|null],
          "percentile_score": [float|null],
          "keywords": [str],
          "windows_and_scores": [{"window": int, "score": float}],
          "windows_without_topic": int|null,
          "correlations": {
            "<metric>": {
              "pearson_r": float,
              "p_value": float,
              "pearson_r_binary": float,
              "p_value_binary": float,
              "n_windows": int,
              "mean_with_topic": float,
              "mean_without_topic": float
            }
          }
        }
      ]
    },
    "params": {
      "use_soft_topic_scores": bool,
      "soft_score_threshold": float|null,
      "soft_top_k": int|null,
      "central_top_n": int|null,
      "centrality_threshold": float,
      "near_top_alpha": float,
      "min_keep": int,
      "block_size": int,
      "permutations": int
    }
  }

- data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_presence_correlations.json
  {
    "metadata": {
      "category": str,
      "text_name": str,
      "filename": str,
      "topic_file": str
    },
    "report": {
      "window_count": int,
      "metric_names": [str],
      "central_topic_presence": {
        "windows_with_central_topic": int,
        "windows_without_central_topic": int,
        "presence_windows": [int],
        "central_max_scores": [float],
        "central_presence_threshold": float|null,
        "correlations": {
          "<metric>": {
            "pearson_r": float,
            "p_value": float,
            "pearson_r_binary": float,
            "p_value_binary": float,
            "n_windows": int,
            "mean_with_topic": float,
            "mean_without_topic": float
          }
        }
      }
    },
    "params": {
      "central_presence_percentile": float,
      "soft_score_threshold": float|null,
      "soft_top_k": int|null,
      "block_size": int,
      "permutations": int
    }
  }

Outputs (aggregates, under output_root):
- <output_root>/<genre>/00_genre_central_topic_presence_correlations.json
  {
    "genre": str,
    "text_count": int,
    "metric_names": [str],
    "metrics": {
      "<metric>": {
        "pearson_r": float,
        "p_value": float,
        "text_count": int,
        "total_windows": int,
        "total_effective_windows": int,
        "fisher_z": float,
        "fisher_z_weight_sum": float
      }
    },
    "texts": [
      {
        "category": str,
        "author": str,
        "text_name": str,
        "filename": str,
        "window_count": int|null,
        "effective_window_count": int|null,
        "block_size": int|null,
        "metric_count": int
      }
    ],
    "params": {
      "r_aggregation": "fisher_z",
      "p_value_aggregation": "stouffer",
      "r_weight": "n_eff-3",
      "p_weight": "sqrt(n_eff-3)",
      "n_eff_method": "ceil(n_windows / block_size), min 1",
      "block_size": int|[int]
    }
  }

- <output_root>/00_central_topic_split_half_stability.json
  {
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [
      {
        "category": str,
        "text_name": str,
        "filename": str,
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float,
        "soft_score_threshold": float|null,
        "soft_top_k": int|null
      }
    ],
    "params": {
      "split_method": "odd_even",
      "soft_score_threshold": [float],
      "soft_top_k": [int]
    }
  }

- <output_root>/<genre>/00_genre_central_topic_split_half_stability.json
  {
    "genre": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even",
      "soft_score_threshold": [float],
      "soft_top_k": [int]
    }
  }

- <output_root>/<genre>/<author>/<author>_central_topic_split_half_stability.json
  {
    "genre": str,
    "author": str,
    "text_count": int,
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "texts": [ ... ],
    "params": {
      "split_method": "odd_even",
      "soft_score_threshold": [float],
      "soft_top_k": [int]
    }
  }

- data/results/00_cross_block_consistency.json
  {
    "block_labels": [str],
    "pair_count": int,
    "overall": {
      "sign_agreement_rate": float,
      "mean_abs_delta_r": float,
      "median_abs_delta_r": float
    },
    "metrics": {
      "<metric>": {
        "pair_count": int,
        "sign_agreement_rate": float,
        "mean_abs_delta_r": float,
        "median_abs_delta_r": float
      }
    },
    "params": {
      "block_labels": [str],
      "output_roots": [str]
    }
  }
"""

import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from tqdm import tqdm

from .d0_significance_stability import (
    AUTHOR_CENTRAL_TOPIC_SPLIT_HALF_TEMPLATE,
    CENTRAL_TOPIC_SPLIT_HALF_FILENAME,
    GENRE_CENTRAL_TOPIC_SPLIT_HALF_FILENAME,
    _build_central_topic_split_half_entry,
    _write_author_central_topic_split_half_summary,
    _write_central_topic_split_half_summary,
    _write_cross_block_consistency_summary,
    _write_genre_central_presence_correlations,
    _write_genre_central_topic_split_half_summary,
)
from .d1_dashboard_metrics import (
    build_central_presence_report,
    build_central_topic_correlations,
    build_topic_correlation_report,
    load_window_metrics,
)
from .x_configs import (
    DEFAULT_CENTRAL_TOPIC_SELECTION_CONFIG,
    DEFAULT_DASHBOARD_CORRELATION_CONFIG,
    DashboardCorrelationConfig,
)
from .z_utils import find_topic_file, find_window_metrics_files, results_path


def _split_report_params(report: Dict[str, object]) -> Tuple[Dict[str, object], Dict[str, object]]:
    if not isinstance(report, dict):
        return {}, {}
    params = report.get("params")
    if not isinstance(params, dict):
        params = {}
    report_body = {key: value for key, value in report.items() if key != "params"}
    return report_body, params


def _build_metadata(window_metrics_path: Path, topic_file: Path) -> Dict[str, object]:
    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name
    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
    }


def _build_topic_dashboard_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: Optional[int],
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    report = build_topic_correlation_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        topics_key="topics",
        block_size=block_size,
        permutations=permutations,
    )
    if not report:
        return None

    metadata = _build_metadata(window_metrics_path, topic_file)
    report_body, params = _split_report_params(report)

    return {
        "metadata": metadata,
        "report": report_body,
        "params": params,
    }

def _build_central_topic_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: Optional[int],
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    central_report = build_central_topic_correlations(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )
    if not central_report:
        return None

    metadata = _build_metadata(window_metrics_path, topic_file)
    report_body, params = _split_report_params(central_report)

    return {
        "metadata": metadata,
        "report": report_body,
        "params": params,
    }


def _build_central_presence_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: Optional[int],
    block_size: int,
    permutations: int,
    central_presence_percentile: float,
) -> Optional[Dict[str, object]]:
    topic_file = find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    presence_report = build_central_presence_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
        central_presence_percentile=central_presence_percentile,
    )
    if not presence_report:
        return None

    metadata = _build_metadata(window_metrics_path, topic_file)
    report_body, params = _split_report_params(presence_report)

    return {
        "metadata": metadata,
        "report": report_body,
        "params": params,
    }

def run_dashboard(
    use_existing: bool = False,
    *,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_top_n: Optional[int] = None,
    block_size: int = 5,
    permutations: int = 2000,
    central_presence_percentile: float = 70.0,
    output_root: Optional[Path] = None,
    authors: Optional[List[str]] = None,
) -> List[Dict[str, object]]:
    """
    Build topic correlation outputs from window metrics and write JSON outputs.

    Outputs (per text):
      data/results/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
      data/results/dashboard/<genre>/<author>/<text>/<text>_central_topic_presence_correlations.json
    Outputs (aggregates):
      data/results/dashboard/<genre>/00_genre_central_topic_presence_correlations.json
    """
    selection_config = DEFAULT_CENTRAL_TOPIC_SELECTION_CONFIG
    if central_top_n is None:
        central_top_n = selection_config.max_topics
    if central_top_n is not None and central_top_n <= 0:
        central_top_n = None

    if output_root is None:
        output_root = results_path("dashboard")
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    window_metric_files = find_window_metrics_files()
    if authors:
        window_metric_files = [
            file for file in window_metric_files if file.parent.parent.name in authors
        ]
    if not window_metric_files:
        return []

    skip_split_half = False
    if use_existing:
        split_half_output_path = output_root / CENTRAL_TOPIC_SPLIT_HALF_FILENAME
        genre_author_pairs = {
            (file.parent.parent.parent.name, file.parent.parent.name)
            for file in window_metric_files
        }
        genre_outputs = {
            output_root / genre / GENRE_CENTRAL_TOPIC_SPLIT_HALF_FILENAME
            for genre, _author in genre_author_pairs
        }
        author_outputs = {
            output_root
            / genre
            / author
            / AUTHOR_CENTRAL_TOPIC_SPLIT_HALF_TEMPLATE.format(author=author)
            for genre, author in genre_author_pairs
        }
        skip_split_half = (
            split_half_output_path.exists()
            and all(path.exists() for path in genre_outputs)
            and all(path.exists() for path in author_outputs)
        )
    central_presence_entries: List[Dict[str, object]] = []
    split_half_entries: List[Dict[str, object]] = []

    for file in tqdm(window_metric_files, desc="Dashboard correlations", ascii=True):
        genre = file.parent.parent.parent.name
        author = file.parent.parent.name
        text_name = file.parent.name
        out_dir = output_root / genre / author / text_name
        out_dir.mkdir(parents=True, exist_ok=True)

        topic_file = out_dir / f"{text_name}_topic_correlations.json"
        central_file = out_dir / f"{text_name}_central_topic_correlations.json"
        presence_file = out_dir / f"{text_name}_central_topic_presence_correlations.json"
        topic_entry = None
        if use_existing and topic_file.exists():
            try:
                with open(topic_file, "r", encoding="utf-8") as f:
                    topic_entry = json.load(f)
            except json.JSONDecodeError:
                topic_entry = None
        if topic_entry is None:
            topic_entry = _build_topic_dashboard_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
            if topic_entry:
                with open(topic_file, "w", encoding="utf-8") as f:
                    json.dump(topic_entry, f, indent=2)

        central_entry = None
        if use_existing and central_file.exists():
            try:
                with open(central_file, "r", encoding="utf-8") as f:
                    central_entry = json.load(f)
            except json.JSONDecodeError:
                central_entry = None
        if central_entry is None:
            central_entry = _build_central_topic_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
        if central_entry:
            with open(central_file, "w", encoding="utf-8") as f:
                json.dump(central_entry, f, indent=2)
            if not skip_split_half:
                split_half_entry = _build_central_topic_split_half_entry(
                    file,
                    central_entry,
                    soft_score_threshold=soft_score_threshold,
                    soft_top_k=soft_top_k,
                )
                if split_half_entry:
                    split_half_entries.append(split_half_entry)

        presence_entry = None
        if use_existing and presence_file.exists():
            try:
                with open(presence_file, "r", encoding="utf-8") as f:
                    presence_entry = json.load(f)
            except json.JSONDecodeError:
                presence_entry = None
        if presence_entry is None:
            presence_entry = _build_central_presence_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
                central_presence_percentile=central_presence_percentile,
            )
        if presence_entry:
            with open(presence_file, "w", encoding="utf-8") as f:
                json.dump(presence_entry, f, indent=2)
            central_presence_entries.append(
                {
                    "category": f"{genre}/{author}",
                    "genre": genre,
                    "author": author,
                    "text_name": text_name,
                    "filename": file.name,
                    "presence_report": presence_entry,
                }
            )

    _write_genre_central_presence_correlations(
        central_presence_entries,
        use_existing=use_existing,
        output_root=output_root,
    )
    if not skip_split_half:
        _write_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_genre_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )
        _write_author_central_topic_split_half_summary(
            split_half_entries,
            use_existing=use_existing,
            output_root=output_root,
        )

    return []

def run_dashboard_with_config(
    use_existing: bool = False,
    *,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_top_n: Optional[int] = None,
    central_presence_percentile: float = 70.0,
    authors: Optional[List[str]] = None,
    config: DashboardCorrelationConfig = DEFAULT_DASHBOARD_CORRELATION_CONFIG,
) -> List[Dict[str, object]]:
    if config.loop_enabled:
        block_sizes = list(config.loop_block_sizes or ())
        if not block_sizes:
            block_sizes = [config.block_size]
        output_roots: List[Path] = []
        block_labels: List[str] = []
        for block_size in block_sizes:
            output_root = Path("data") / "results" / config.loop_output_template.format(
                block_size=block_size
            )
            output_roots.append(output_root)
            block_labels.append(output_root.name)
            run_dashboard(
                use_existing=use_existing,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=config.permutations,
                central_presence_percentile=central_presence_percentile,
                output_root=output_root,
                authors=authors,
            )
        _write_cross_block_consistency_summary(
            output_roots,
            block_labels,
            use_existing=use_existing,
        )
        return []

    return run_dashboard(
        use_existing=use_existing,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=config.block_size,
        permutations=config.permutations,
        central_presence_percentile=central_presence_percentile,
        authors=authors,
    )

if __name__ == "__main__":
    run_dashboard_with_config()
