"""
Dashboard orchestrator: build topic correlation outputs for window metrics.

Metrics grouped by:
- Unexpectedness: avg_token_surprisal, max_token_surprisal, surprisal_variance
- Lexical: lexical_density, lexical_diversity_mattr, avg_word_freq, normalized_freq, information_content
- Structure: mean_dependency_depth, max_dependency_depth, clause_density, avg_dependents_per_head,
  clause_ratios, avg_mean_dependency_distance, avg_median_depth, depth_skew
- Discourse: explicit_connectives_per_token, connective_counts_per_token, tense_shift, entity_overlap_rate

Assumes window metrics exist under data/analytics/window_metrics/<category>/<name>/
generated by d_window_metrics.run_windowed_metrics.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional

from c5_dashboard_metrics import (
    build_central_report,
    build_topic_correlation_report,
    central_topics,
    load_window_metrics,
)
from z_utils import analytics_path

def _find_topic_file(window_metrics_path: Path) -> Optional[Path]:
    text_dir = window_metrics_path.parent
    author_dir = window_metrics_path.parent.parent
    genre_dir = window_metrics_path.parent.parent.parent
    topic_root = analytics_path("topic") / genre_dir.name / author_dir.name / text_dir.name
    candidates = [
        topic_root / f"{text_dir.name}_clustered_topics.json",
        topic_root / f"{text_dir.name}_topics.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None

def _find_window_metrics_files() -> List[Path]:
    root = analytics_path("window")
    if not root.exists():
        return []
    return sorted(root.glob("*/*/*/*_window_metrics.json"))

def _build_topic_dashboard_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = _find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    report = build_topic_correlation_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        topics_key="topics",
        block_size=block_size,
        permutations=permutations,
    )
    if not report:
        return None

    central_report = build_central_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "report": report,
        "central_topics": central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }

def _build_central_topic_entry(
    window_metrics_path: Path,
    *,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = _find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = load_window_metrics(window_metrics_path)
    topics_data = load_window_metrics(topic_file)
    central_report = build_central_report(
        window_data,
        topics_data,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = f"{window_metrics_path.parent.parent.parent.name}/{window_metrics_path.parent.parent.name}"
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "central_topics": central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }

def run_dashboard(
    use_existing: bool = False,
    *,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_top_n: int = 5,
    block_size: int = 5,
    permutations: int = 2000,
) -> List[Dict[str, object]]:
    """
    Build topic correlation outputs from window metrics and write JSON outputs.

    Outputs (per text):
      data/analytics/dashboard/<genre>/<author>/<text>/<text>_topic_correlations.json
      data/analytics/dashboard/<genre>/<author>/<text>/<text>_central_topic_correlations.json
    """
    output_root = analytics_path("dashboard")
    output_root.mkdir(parents=True, exist_ok=True)

    window_metric_files = _find_window_metrics_files()

    for file in window_metric_files:
        genre = file.parent.parent.parent.name
        author = file.parent.parent.name
        text_name = file.parent.name
        out_dir = output_root / genre / author / text_name
        out_dir.mkdir(parents=True, exist_ok=True)

        topic_file = out_dir / f"{text_name}_topic_correlations.json"
        central_file = out_dir / f"{text_name}_central_topic_correlations.json"
        topic_entry = None
        if use_existing and topic_file.exists():
            try:
                with open(topic_file, "r", encoding="utf-8") as f:
                    topic_entry = json.load(f)
            except json.JSONDecodeError:
                topic_entry = None
        if topic_entry is None:
            topic_entry = _build_topic_dashboard_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
            if topic_entry:
                with open(topic_file, "w", encoding="utf-8") as f:
                    json.dump(topic_entry, f, indent=2)

        central_entry = None
        if use_existing and central_file.exists():
            try:
                with open(central_file, "r", encoding="utf-8") as f:
                    central_entry = json.load(f)
            except json.JSONDecodeError:
                central_entry = None
        if central_entry is None:
            central_entry = _build_central_topic_entry(
                file,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
            if central_entry:
                with open(central_file, "w", encoding="utf-8") as f:
                    json.dump(central_entry, f, indent=2)

    return []

if __name__ == "__main__":
    run_dashboard()
