import json
import math
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np

from c4_topic_modeling import (
    build_topic_window_metrics,
    collect_soft_topic_mentions,
    collect_topic_mentions,
)
from z_utils import analytics_path

"""
Dashboard orchestrator: summarize key metrics into a compact table.

Metrics grouped by:
- Cohesion: entity_overlap_rate (adjacent sentence overlap)
- Unexpectedness: avg_token_surprisal, max_token_surprisal, surprisal_variance
- Lexical: lexical_density
- Structure: mean_dependency_depth, max_dependency_depth, clause_density, avg_dependents_per_head
- Roles: agent_rate_per_clause, patient_rate_per_clause, role_coverage

Assumes window metrics exist under data/analytics/window_metrics/<category>/<name>/
generated by d_window_metrics.run_windowed_metrics.
"""


def _safe_mean(values: List[Optional[float]]) -> Optional[float]:
    clean = [v for v in values if isinstance(v, (int, float))]
    if not clean:
        return None
    return sum(clean) / len(clean)


def _safe_max(values: List[Optional[float]]) -> Optional[float]:
    clean = [v for v in values if isinstance(v, (int, float))]
    if not clean:
        return None
    return max(clean)


def _safe_min(values: List[Optional[float]]) -> Optional[float]:
    clean = [v for v in values if isinstance(v, (int, float))]
    if not clean:
        return None
    return min(clean)


def _load_window_metrics(path: Path) -> Dict[str, object]:
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def _is_number(value: object) -> bool:
    return isinstance(value, (int, float)) and not (isinstance(value, float) and math.isnan(value))


def _flatten_numeric_metrics(entry: Dict[str, object], prefix: str) -> Dict[str, float]:
    metrics: Dict[str, float] = {}
    for key, value in entry.items():
        if key in {"start_sentence", "end_sentence"}:
            continue
        metric_key = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            for sub_key, sub_val in value.items():
                if _is_number(sub_val):
                    metrics[f"{metric_key}.{sub_key}"] = float(sub_val)
        elif _is_number(value):
            metrics[metric_key] = float(value)
    return metrics


def _collect_window_tables(window_data: Dict[str, object]) -> List[Dict[str, float]]:
    """
    Flatten per-window metrics from the window analysis result so they can be
    correlated against topic presence.
    """
    metrics_by_name: Dict[str, List[Dict[str, object]]] = {}

    syntax_windows = window_data.get("syntax", {}).get("windows", [])
    if syntax_windows:
        metrics_by_name["syntax"] = syntax_windows

    lex_windows = window_data.get("lexico_semantics", {}).get("windows", [])
    if lex_windows:
        metrics_by_name["lexico_semantics"] = lex_windows

    discourse_windows = window_data.get("discourse", {}).get("windows", [])
    if discourse_windows:
        metrics_by_name["discourse"] = discourse_windows

    log_prob_windows = window_data.get("log_prob", {}).get("windows", [])
    if log_prob_windows:
        metrics_by_name["log_prob"] = log_prob_windows

    info_content_windows = window_data.get("information_content_metrics", [])
    if info_content_windows:
        metrics_by_name["information_content_metrics"] = info_content_windows

    if not metrics_by_name:
        return []

    lengths = {name: len(entries) for name, entries in metrics_by_name.items()}
    if len(set(lengths.values())) > 1:
        window_count = min(lengths.values())
    else:
        window_count = next(iter(lengths.values()))
    if window_count <= 0:
        return []
    table: List[Dict[str, float]] = []
    for idx in range(window_count):
        row: Dict[str, float] = {}
        for name, entries in metrics_by_name.items():
            row.update(_flatten_numeric_metrics(entries[idx], name))
        table.append(row)
    return table


def _find_topic_file(window_metrics_path: Path) -> Optional[Path]:
    category_dir = window_metrics_path.parent.parent
    text_dir = window_metrics_path.parent
    topic_root = analytics_path("topic") / category_dir.name / text_dir.name
    candidates = [
        topic_root / f"{text_dir.name}_clustered_topics.json",
        topic_root / f"{text_dir.name}_topics.json",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _pearson_correlation(x: List[float], y: List[float]) -> Optional[float]:
    if len(x) < 2 or len(y) < 2:
        return None
    x_arr = np.array(x, dtype=float)
    y_arr = np.array(y, dtype=float)
    if x_arr.std() == 0 or y_arr.std() == 0:
        return None
    corr = float(np.corrcoef(x_arr, y_arr)[0, 1])
    if math.isnan(corr):
        return None
    return corr


def _block_permutation_p_value(
    x: List[float],
    y: List[float],
    *,
    block_size: int,
    permutations: int,
    rng: np.random.Generator,
) -> Optional[float]:
    if len(x) < 2 or len(y) < 2:
        return None
    if block_size <= 0 or permutations <= 0:
        return None
    observed = _pearson_correlation(x, y)
    if observed is None:
        return None
    n = len(x)
    block_size = min(block_size, n)
    blocks = [x[i : i + block_size] for i in range(0, n, block_size)]
    if not blocks:
        return None
    counts = 0
    for _ in range(permutations):
        perm_blocks = rng.permutation(len(blocks))
        shuffled = [val for idx in perm_blocks for val in blocks[idx]]
        shuffled = shuffled[:n]
        corr = _pearson_correlation(shuffled, y)
        if corr is None:
            continue
        if abs(corr) >= abs(observed):
            counts += 1
    return (counts + 1) / (permutations + 1)


def _topic_keywords(topics_data: Dict[str, object]) -> Dict[int, List[str]]:
    topics = topics_data.get("topics", []) if isinstance(topics_data, dict) else []
    mapping: Dict[int, List[str]] = {}
    for topic in topics:
        if not isinstance(topic, dict):
            continue
        topic_id = topic.get("topic_id")
        keywords = topic.get("keywords", [])
        if isinstance(topic_id, int):
            mapping[topic_id] = keywords if isinstance(keywords, list) else []
    return mapping


def _central_topics(
    topics_data: Dict[str, object],
    top_n: int = 5,
) -> List[Dict[str, object]]:
    topics = topics_data.get("topics", []) if isinstance(topics_data, dict) else []
    metrics = ["coherence", "exclusivity", "prevalence", "persistence"]
    values: Dict[str, List[float]] = {metric: [] for metric in metrics}
    entries: List[Tuple[int, List[str], Dict[str, float]]] = []
    for topic in topics:
        if not isinstance(topic, dict):
            continue
        topic_id = topic.get("topic_id")
        stats = topic.get("stats") or {}
        if not isinstance(topic_id, int) or not isinstance(stats, dict):
            continue
        keywords = topic.get("keywords", [])
        stats_clean: Dict[str, float] = {}
        for metric in metrics:
            val = stats.get(metric)
            if _is_number(val):
                stats_clean[metric] = float(val)
                values[metric].append(float(val))
        if stats_clean:
            entries.append((topic_id, keywords if isinstance(keywords, list) else [], stats_clean))

    if not entries:
        return []

    mins = {metric: min(values[metric]) for metric in metrics if values[metric]}
    maxs = {metric: max(values[metric]) for metric in metrics if values[metric]}

    def _norm(metric: str, val: float) -> float:
        lo = mins.get(metric)
        hi = maxs.get(metric)
        if lo is None or hi is None or hi == lo:
            return 0.0
        return (val - lo) / (hi - lo)

    ranked = []
    for topic_id, keywords, stats in entries:
        score = 0.0
        used = 0
        for metric, val in stats.items():
            score += _norm(metric, val)
            used += 1
        if used == 0:
            continue
        ranked.append(
            {
                "topic_id": topic_id,
                "score": score,
                "keywords": keywords,
                "stats": stats,
            }
        )

    ranked.sort(key=lambda row: row["score"], reverse=True)
    return ranked[:top_n]


def _build_topic_correlation_report(
    window_data: Dict[str, object],
    topics_data: Dict[str, object],
    *,
    correlation_threshold: float = 0.3,
    min_topic_windows: int = 3,
    min_windows: int = 5,
    use_soft_topic_scores: bool = True,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_only: bool = False,
    central_top_n: int = 5,
    variance_only: bool = False,
    topics_key: str = "topics",
    block_size: int = 5,
    permutations: int = 2000,
) -> Dict[str, object]:
    topic_mentions = (
        collect_soft_topic_mentions(
            topics_data,
            score_threshold=soft_score_threshold,
            top_k=soft_top_k,
        )
        if use_soft_topic_scores
        else collect_topic_mentions(topics_data)
    )
    window_entries = window_data.get("syntax", {}).get("windows", [])
    if not topic_mentions or not window_entries:
        return {}

    topic_metrics = build_topic_window_metrics(topic_mentions, window_entries)
    window_table = _collect_window_tables(window_data)
    if not window_table or len(window_table) != len(topic_metrics):
        return {}

    metric_names = sorted(window_table[0].keys()) if window_table else []
    metric_names = [
        name
        for name in metric_names
        if not any(token in name for token in ("sentence_index", "start_sentence", "end_sentence"))
    ]
    if variance_only:
        metric_names = [name for name in metric_names if "variance" in name]
        if not metric_names:
            return {}
    topics = set()
    for entry in topic_metrics:
        topics.update(entry.get("topic_counts", {}).keys())

    central_topics = _central_topics(topics_data, top_n=central_top_n)
    if central_only and central_topics:
        topics = {entry["topic_id"] for entry in central_topics}

    keyword_map = _topic_keywords(topics_data)
    topic_reports: Dict[int, Dict[str, object]] = {}

    rng = np.random.default_rng(42)

    for topic_id in sorted(topics):
        values_by_metric: Dict[str, List[Tuple[float, float]]] = {name: [] for name in metric_names}
        with_topic_count = 0
        without_topic_count = 0

        for idx, window_row in enumerate(window_table):
            topic_count = topic_metrics[idx].get("topic_counts", {}).get(topic_id, 0)
            present = 1.0 if topic_count >= 1 else 0.0
            with_topic_count += 1 if present else 0
            without_topic_count += 0 if present else 1
            for metric in metric_names:
                val = window_row.get(metric)
                if _is_number(val):
                    values_by_metric[metric].append((present, float(val)))

        if with_topic_count < min_topic_windows or without_topic_count < min_topic_windows:
            continue

        metric_correlations: Dict[str, object] = {}
        for metric, pairs in values_by_metric.items():
            if len(pairs) < min_windows:
                continue
            presences = [p for p, _ in pairs]
            values = [v for _, v in pairs]
            values_with = [v for p, v in pairs if p >= 1]
            values_without = [v for p, v in pairs if p < 1]
            if len(values_with) < min_topic_windows or len(values_without) < min_topic_windows:
                continue
            corr = _pearson_correlation(presences, values)
            if corr is None or abs(corr) < correlation_threshold:
                continue
            p_value = _block_permutation_p_value(
                presences,
                values,
                block_size=block_size,
                permutations=permutations,
                rng=rng,
            )
            metric_correlations[metric] = {
                "pearson_r": corr,
                "p_value": p_value,
                "n": len(values),
                "mean_with_topic": _safe_mean(values_with),
                "mean_without_topic": _safe_mean(values_without),
            }

        if metric_correlations:
            topic_reports[topic_id] = {
                "keywords": keyword_map.get(topic_id, []),
                "windows_with_topic": with_topic_count,
                "windows_without_topic": without_topic_count,
                "correlations": metric_correlations,
            }

    if not topic_reports:
        return {}

    return {
        "window_count": len(window_table),
        "metric_names": metric_names,
        topics_key: topic_reports,
        "params": {
            "correlation_threshold": correlation_threshold,
            "min_topic_windows": min_topic_windows,
            "min_windows": min_windows,
            "use_soft_topic_scores": use_soft_topic_scores,
            "soft_score_threshold": soft_score_threshold,
            "soft_top_k": soft_top_k,
            "central_only": central_only,
            "central_top_n": central_top_n,
            "variance_only": variance_only,
            "block_size": block_size,
            "permutations": permutations,
        },
    }


def _build_central_report(
    window_data: Dict[str, object],
    topics_data: Dict[str, object],
    *,
    correlation_threshold: float,
    min_topic_windows: int,
    min_windows: int,
    use_soft_topic_scores: bool,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Dict[str, object]:
    report = _build_topic_correlation_report(
        window_data,
        topics_data,
        correlation_threshold=correlation_threshold,
        min_topic_windows=min_topic_windows,
        min_windows=min_windows,
        use_soft_topic_scores=use_soft_topic_scores,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_only=True,
        central_top_n=central_top_n,
        variance_only=False,
        topics_key="central_topics",
        block_size=block_size,
        permutations=permutations,
    )
    central_ranked = _central_topics(topics_data, top_n=central_top_n)
    ordered_topics = []
    for row in central_ranked:
        topic_id = row.get("topic_id")
        if not isinstance(topic_id, int):
            continue
        correlation_entry = report.get("central_topics", {}).get(topic_id, {})
        ordered_topics.append(
            {
                "topic_id": topic_id,
                "score": row.get("score"),
                "keywords": row.get("keywords", []),
                "stats": row.get("stats", {}),
                "correlations": correlation_entry.get("correlations", {}),
                "windows_with_topic": correlation_entry.get("windows_with_topic"),
                "windows_without_topic": correlation_entry.get("windows_without_topic"),
            }
        )

    report["central_topics_ordered"] = ordered_topics
    return report


def _extract_unexpectedness_metrics(window_data: Dict[str, object]) -> Dict[str, Optional[float]]:
    log_prob = window_data.get("log_prob", {}) if isinstance(window_data, dict) else {}
    sentences = log_prob.get("sentences", []) if isinstance(log_prob, dict) else []
    if not isinstance(sentences, list):
        sentences = []

    mean_surprisals = []
    variance_values = []

    for sent in sentences:
        if not isinstance(sent, dict):
            continue
        sent_surprisal = sent.get("sentence_surprisal_metrics", {})
        if not isinstance(sent_surprisal, dict):
            continue
        mean_surprisal = sent_surprisal.get("mean_surprisal")
        variance = sent_surprisal.get("surprisal_variance")
        num_tokens = sent_surprisal.get("num_tokens")
        if isinstance(mean_surprisal, (int, float)) and isinstance(num_tokens, (int, float)) and num_tokens > 0:
            mean_surprisals.append(mean_surprisal)
        if isinstance(variance, (int, float)):
            variance_values.append(variance)

    max_surprisal = _safe_max(mean_surprisals)

    return {
        "avg_token_surprisal": _safe_mean(mean_surprisals),
        "max_token_surprisal": max_surprisal,
        "surprisal_variance": _safe_mean(variance_values),
    }


def _extract_cohesion_metrics(window_data: Dict[str, object]) -> Dict[str, Optional[float]]:
    discourse = window_data.get("discourse", {}) if isinstance(window_data, dict) else {}
    windows = discourse.get("windows", []) if isinstance(discourse, dict) else []
    if not isinstance(windows, list):
        windows = []
    overlap_rates = [
        window.get("entity_overlap_ratio")
        for window in windows
        if isinstance(window, dict) and isinstance(window.get("entity_overlap_ratio"), (int, float))
    ]
    return {"entity_overlap_rate": _safe_mean(overlap_rates)}


def _extract_lexical_metrics(window_data: Dict[str, object]) -> Dict[str, Optional[float]]:
    lexico = window_data.get("lexico_semantics", {}) if isinstance(window_data, dict) else {}
    windows = lexico.get("windows", []) if isinstance(lexico, dict) else []
    if not isinstance(windows, list):
        windows = []
    densities = [
        window.get("lexical_density")
        for window in windows
        if isinstance(window, dict) and isinstance(window.get("lexical_density"), (int, float))
    ]
    return {"lexical_density": _safe_mean(densities)}


def _extract_structure_metrics(window_data: Dict[str, object]) -> Dict[str, Optional[float]]:
    syntax = window_data.get("syntax", {}) if isinstance(window_data, dict) else {}
    windows = syntax.get("windows", []) if isinstance(syntax, dict) else []
    if not isinstance(windows, list):
        windows = []

    mean_depths = []
    max_depths = []
    clauses = []
    dependents = []

    for window in windows:
        if not isinstance(window, dict):
            continue
        mean_depths.append(window.get("mean_depth"))
        max_depths.append(window.get("max_depth"))
        clause_counts = window.get("clause_counts", {})
        if isinstance(clause_counts, dict):
            clause_total = sum(
                val for val in clause_counts.values() if isinstance(val, (int, float))
            )
            clauses.append(clause_total)
        dep_per_head = window.get("avg_dependents_per_head", {})
        if isinstance(dep_per_head, dict):
            dep_vals = [val for val in dep_per_head.values() if isinstance(val, (int, float))]
            dependents.append(_safe_mean(dep_vals))

    clause_density = _safe_mean(clauses)
    return {
        "mean_dependency_depth": _safe_mean(mean_depths),
        "max_dependency_depth": _safe_max(max_depths),
        "clause_density": clause_density,
        "avg_dependents_per_head": _safe_mean(dependents),
    }


def _extract_role_metrics(window_data: Dict[str, object]) -> Dict[str, Optional[float]]:
    lexico = window_data.get("lexico_semantics", {}) if isinstance(window_data, dict) else {}
    windows = lexico.get("windows", []) if isinstance(lexico, dict) else []
    if not isinstance(windows, list):
        windows = []

    agent_rates = []
    patient_rates = []
    role_coverages = []

    for window in windows:
        if not isinstance(window, dict):
            continue
        num_clauses = window.get("num_clauses")
        num_agents = window.get("num_agents")
        num_patients = window.get("num_patients")
        role_count = window.get("role_count")

        if isinstance(num_clauses, (int, float)) and num_clauses > 0:
            if isinstance(num_agents, (int, float)):
                agent_rates.append(num_agents / num_clauses)
            if isinstance(num_patients, (int, float)):
                patient_rates.append(num_patients / num_clauses)
            if isinstance(role_count, (int, float)):
                role_coverages.append(role_count / num_clauses)

    return {
        "agent_rate_per_clause": _safe_mean(agent_rates),
        "patient_rate_per_clause": _safe_mean(patient_rates),
        "role_coverage": _safe_mean(role_coverages),
    }


def build_dashboard_row(window_metrics_path: Path) -> Dict[str, object]:
    window_data = _load_window_metrics(window_metrics_path)
    meta = window_data.get("meta", {}) if isinstance(window_data, dict) else {}
    row = {
        "filename": meta.get("filename", window_metrics_path.name),
        "window_size": meta.get("window_size"),
        "num_sentences": meta.get("num_sentences"),
    }
    row.update(_extract_cohesion_metrics(window_data))
    row.update(_extract_unexpectedness_metrics(window_data))
    row.update(_extract_lexical_metrics(window_data))
    row.update(_extract_structure_metrics(window_data))
    row.update(_extract_role_metrics(window_data))
    return row


def _find_window_metrics_files() -> List[Path]:
    root = analytics_path("window")
    if not root.exists():
        return []
    return sorted(root.glob("*/*/*_window_metrics.json"))


def _build_topic_dashboard_entry(
    window_metrics_path: Path,
    *,
    correlation_threshold: float,
    min_topic_windows: int,
    min_windows: int,
    use_soft_topic_scores: bool,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    central_only: bool,
    variance_only: bool,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = _find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = _load_window_metrics(window_metrics_path)
    topics_data = _load_window_metrics(topic_file)
    report = _build_topic_correlation_report(
        window_data,
        topics_data,
        correlation_threshold=correlation_threshold,
        min_topic_windows=min_topic_windows,
        min_windows=min_windows,
        use_soft_topic_scores=use_soft_topic_scores,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_only=central_only,
        central_top_n=central_top_n,
        variance_only=variance_only,
        topics_key="topics",
        block_size=block_size,
        permutations=permutations,
    )
    if not report:
        return None

    central_report = _build_central_report(
        window_data,
        topics_data,
        correlation_threshold=correlation_threshold,
        min_topic_windows=min_topic_windows,
        min_windows=min_windows,
        use_soft_topic_scores=use_soft_topic_scores,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = window_metrics_path.parent.parent.name
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "report": report,
        "central_topics": _central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }


def _build_central_topic_entry(
    window_metrics_path: Path,
    *,
    correlation_threshold: float,
    min_topic_windows: int,
    min_windows: int,
    use_soft_topic_scores: bool,
    soft_score_threshold: Optional[float],
    soft_top_k: Optional[int],
    central_top_n: int,
    block_size: int,
    permutations: int,
) -> Optional[Dict[str, object]]:
    topic_file = _find_topic_file(window_metrics_path)
    if not topic_file:
        return None

    window_data = _load_window_metrics(window_metrics_path)
    topics_data = _load_window_metrics(topic_file)
    central_report = _build_central_report(
        window_data,
        topics_data,
        correlation_threshold=correlation_threshold,
        min_topic_windows=min_topic_windows,
        min_windows=min_windows,
        use_soft_topic_scores=use_soft_topic_scores,
        soft_score_threshold=soft_score_threshold,
        soft_top_k=soft_top_k,
        central_top_n=central_top_n,
        block_size=block_size,
        permutations=permutations,
    )

    category = window_metrics_path.parent.parent.name
    text_name = window_metrics_path.parent.name

    return {
        "category": category,
        "text_name": text_name,
        "filename": window_metrics_path.name,
        "topic_file": str(topic_file),
        "central_topics": _central_topics(topics_data, top_n=central_top_n),
        "central_report": central_report,
    }


def run_dashboard(
    use_existing: bool = True,
    *,
    correlation_threshold: float = 0.3,
    min_topic_windows: int = 3,
    min_windows: int = 5,
    use_soft_topic_scores: bool = True,
    soft_score_threshold: Optional[float] = 0.5,
    soft_top_k: Optional[int] = 3,
    central_top_n: int = 5,
    central_only: bool = False,
    variance_only: bool = False,
    block_size: int = 5,
    permutations: int = 2000,
) -> List[Dict[str, object]]:
    """
    Build the dashboard table from window metrics and write JSON outputs.

    Outputs (per text):
      data/analytics/dashboard/<category>/<name>/<name>_dashboard.json
      data/analytics/dashboard/<category>/<name>/<name>_topic_correlations.json
      data/analytics/dashboard/<category>/<name>/<name>_central_topic_correlations.json
    Also writes aggregated tables at:
      data/analytics/dashboard/dashboard_table.json
      data/analytics/dashboard/dashboard_topic_correlations.json
      data/analytics/dashboard/dashboard_central_topic_correlations.json
    """
    output_root = analytics_path("dashboard")
    output_root.mkdir(parents=True, exist_ok=True)
    aggregate_table_file = output_root / "dashboard_table.json"
    aggregate_topic_file = output_root / "dashboard_topic_correlations.json"
    aggregate_central_file = output_root / "dashboard_central_topic_correlations.json"

    rows: List[Dict[str, object]] = []
    topic_reports: List[Dict[str, object]] = []

    window_metric_files = _find_window_metrics_files()

    for file in window_metric_files:
        category = file.parent.parent.name
        text_name = file.parent.name
        out_dir = output_root / category / text_name
        out_dir.mkdir(parents=True, exist_ok=True)

        row_file = out_dir / f"{text_name}_dashboard.json"
        if use_existing and row_file.exists():
            try:
                with open(row_file, "r", encoding="utf-8") as f:
                    row = json.load(f)
            except json.JSONDecodeError:
                row = None
        else:
            row = build_dashboard_row(file)
            with open(row_file, "w", encoding="utf-8") as f:
                json.dump(row, f, indent=2)

        if isinstance(row, dict):
            rows.append(row)

        topic_file = out_dir / f"{text_name}_topic_correlations.json"
        central_file = out_dir / f"{text_name}_central_topic_correlations.json"
        topic_entry = None
        if use_existing and topic_file.exists():
            try:
                with open(topic_file, "r", encoding="utf-8") as f:
                    topic_entry = json.load(f)
            except json.JSONDecodeError:
                topic_entry = None
        if topic_entry is None:
            topic_entry = _build_topic_dashboard_entry(
                file,
                correlation_threshold=correlation_threshold,
                min_topic_windows=min_topic_windows,
                min_windows=min_windows,
                use_soft_topic_scores=use_soft_topic_scores,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                central_only=central_only,
                variance_only=variance_only,
                block_size=block_size,
                permutations=permutations,
            )
            if topic_entry:
                with open(topic_file, "w", encoding="utf-8") as f:
                    json.dump(topic_entry, f, indent=2)

        central_entry = None
        if use_existing and central_file.exists():
            try:
                with open(central_file, "r", encoding="utf-8") as f:
                    central_entry = json.load(f)
            except json.JSONDecodeError:
                central_entry = None
        if central_entry is None:
            central_entry = _build_central_topic_entry(
                file,
                correlation_threshold=correlation_threshold,
                min_topic_windows=min_topic_windows,
                min_windows=min_windows,
                use_soft_topic_scores=use_soft_topic_scores,
                soft_score_threshold=soft_score_threshold,
                soft_top_k=soft_top_k,
                central_top_n=central_top_n,
                block_size=block_size,
                permutations=permutations,
            )
            if central_entry:
                with open(central_file, "w", encoding="utf-8") as f:
                    json.dump(central_entry, f, indent=2)

        if topic_entry:
            topic_reports.append(topic_entry)
        if central_entry:
            topic_reports.append(central_entry)

    with open(aggregate_table_file, "w", encoding="utf-8") as f:
        json.dump(rows, f, indent=2)

    with open(aggregate_topic_file, "w", encoding="utf-8") as f:
        json.dump(topic_reports, f, indent=2)

    with open(aggregate_central_file, "w", encoding="utf-8") as f:
        json.dump(
            [entry for entry in topic_reports if "central_topics" in entry],
            f,
            indent=2,
        )

    return rows


if __name__ == "__main__":
    run_dashboard()
